# Generated by Django 5.1.1 on 2024-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_etudiant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='telephone',
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default='une biographie du professeur', max_length=500),
            preserve_default=False,
        ),
    ]
