# Generated by Django 5.1.1 on 2024-11-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_teacher_telephone_teacher_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
