# Generated by Django 5.1.1 on 2024-11-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0030_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
